FROM registry.access.redhat.com/ubi9/ubi-minimal as tools-builder

ARG MAVEN_VERSION=3.9.9
ARG QUARKUS_VERSION=3.15.2
ARG NODE_VERSION=v22.11.0
ARG MANDREL_VERSION=23.1.5.0-Final
ARG MANDREL_JAVA_VERSION=java21
ARG GO_VERSION=1.23.3
ARG OPERATOR_SDK_VERSION=v1.38.0

COPY fetch-tools.sh /fetch-tools.sh

RUN microdnf --disableplugin=subscription-manager install -y bash tar gzip zip xz unzip ; \
  chmod +x /fetch-tools.sh ; \
  /fetch-tools.sh

FROM registry.access.redhat.com/ubi9/ubi-minimal

ARG USER_HOME_DIR="/home/user"
ARG WORK_DIR="/projects"
ARG JAVA_PACKAGE=java-21-openjdk-devel
ARG JAVA_HOME_DIR=/etc/alternatives/jre_21_openjdk
ARG INSTALL_PACKAGES="procps-ng openssl compat-openssl11 libbrotli git tar gzip zip xz unzip which shadow-utils bash zsh vi wget jq podman buildah skopeo podman-docker glibc-devel zlib-devel gcc libffi-devel libstdc++-devel gcc-c++ glibc-langpack-en ca-certificates python3-pip python3-devel fuse-overlayfs"

ENV HOME=${USER_HOME_DIR}
ENV BUILDAH_ISOLATION=chroot
ENV GRAALVM_HOME=/usr/local/tools/graalvm
ENV JAVA_HOME=${JAVA_HOME_DIR}
ENV PATH=${PATH}:/usr/local/tools/bin:/usr/local/tools/node/bin
ENV JBANG_DIR=/usr/local/tools/jbang

COPY --from=tools-builder /tools/ /usr/local/tools
COPY --chown=0:0 entrypoint.sh /

RUN microdnf --disableplugin=subscription-manager install -y ${INSTALL_PACKAGES} ${JAVA_PACKAGE}; \
  microdnf update -y ; \
  microdnf clean all ; \
  mkdir -p ${WORK_DIR} ; \
  mkdir -p /usr/local/bin ; \
  npm install -g @angular/cli ; \
  npm install -g serverless ; \
  mkdir -p ${JBANG_DIR} ; \
  curl -Ls https://sh.jbang.dev | bash -s - app setup ; \
  ln -s ${JBANG_DIR}/bin/jbang /usr/local/tools/bin/jbang ; \
  chmod +x /entrypoint.sh ; \
  #
  # Setup for rootless podman
  #
  setcap cap_setuid+ep /usr/bin/newuidmap ; \
  setcap cap_setgid+ep /usr/bin/newgidmap ; \
  mkdir -p ${HOME}/.config/containers ; \
  touch /etc/subgid /etc/subuid ; \
  chgrp -R 0 /home ; \
  chmod -R g=u /home /etc/passwd /etc/group /etc/subuid /etc/subgid ${WORK_DIR}

USER 10001
WORKDIR ${WORK_DIR}
ENTRYPOINT ["/usr/libexec/podman/catatonit","--","/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]